config/routes.rb
Rails.application.routes.draw do
  get 'items/create'
  resources :lists do #creates 7 restful routes.  to view enter 'rake routes' in terminal.
  resources :items
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
#class Item  < ActiveRecord::Base
    belongs_to :list #adds methods to my model
    validates :description, presence: true, length: { minimum: 2 }
    validates :description, uniqueness: true

    STATUS = {
        :incomplete => 0,
        :complete => 1
    }
    #use hash above to set up key 10:00 v3
    #clearly define meaning of #0 || #1 in context
    def complete?
        self.status == STATUS[:complete]    
        #self.status == 1
    end

    def incomplete?
        self.status == STATUS[:incomplete]
        #self.status == 0
    end

    def complete!
        self.status = STATUS[:complete]
        self.save
        #self.status == 0
    end

    def incomplete!
        self.status = STATUS[:incomplete]
        self.save
        #self.status == 0
    end


end

app/models/list.rb
class List < ApplicationRecord
#class List < ActiveRecord::Base
    has_many :items #adds methods to my model
    #validates :name, presence => true
    validates :name, presence: true, length: { minimum: 2 }
    validates :name, uniqueness: true
#validates :presence => :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id]) #find parent
    @item = @list.items.build(item_params)
    if @item.save
    #raise params.inspect
    redirect_to list_path(@list)
    else
      render "lists/show"
    end
  end


# def create
# #raise params.inspect
#     @item = Item.new
#     @item.description = params[:item][:description]
#     @item.save
#50th
    #redirect_to item_path(@item)
  # end
# PATCH - /lists/:list_id/items/:id

def update
  #raise params.inspect
  #what do I want to update?
  @item = Item.find(params[:id])
  @item.update(item_params)

  redirect_to list_path(@item.list)

  # @item.status = params[:id][:status]
  # @item.save
end

def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to list_path(@item.list)
  end



private
  def item_params
  params.require(:item).permit(:description, :status)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @list = List.new
    @lists = List.all
    # render 'lists/index.html.erb'
#    raise @lists.inspect
    # implicit rendering
    # render 'site/index'
    # render 'controller/action'
  end

  def show
    @list = List.find(params[:id])
    @item = Item.new
    #@item = @list.items.build #this was casing an error 22:00 v3
  end

  def create
#raise params.inspect
    @list = List.new(list_params)
    #@list.name = params[:list][:name]
    if @list.save
      redirect_to list_url(@list) #50th
#      redirect_to list_path(@list) #50th
    else
      @lists = List.all
      render :index
    end
  end

  #mass assignment
private
  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    # implicit rendering
    # render 'site/index'
    # render 'controller/action'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper #actionview will run this file and other all helpers
    def li_class_for_item(item)
        "completed" if item.complete?
    end

    def li_for_item(item)
         content_tag_for :li, item, :class => li_class_for_item(item) do
            yield
         end
    end

    def form_for_item_status(item)
        form_for([item.list, item]) do |f|
            f.check_box :status, :class => "toggle", :checked => item.complete?
    end
end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/items/_item_li.html.erb
<%= li_for_item(item) do %>
    <div class="view">
        <%= form_for_item_status(item) do %>
        Rando text
    <% end %>
    <label> <%= item.description %>  </label>

    <input type="submit" name="" id="">

<form action="<%= list_item_path(item.list ,item)%>" method="post"/>
<button type="submit" class="button"></button>

<input type="hidden" name="_method" value="delete">
<button class="close" </button>
    <span class="close">x</span>
</div>
</form>


<% end %>

app/views/items/_item_li_v4.html.erb
<li class="<%= 'completed' if item.complete? %>"></li>
<div class="view">
    <%= form_for([@list, item]) do |f| %>
    <%= f.check_box :status, :class => "toggle", :checked => (true if item.complete?) %>

    <label> <%= item.description %></label>
    <input type="submit" name="" id="">
    <% end %>
</div>
</li>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/index.html.erb
<section class="grocerylisterapp">
    <header class="header">
        <h1>Your Lists</h1>
      <%= form_for(@list) do |f| %>
      <%= f.text_field :name, :class => "new-item" %>
      <%= f.submit :style => "display: none" %>
         <%  end %>
</form>
    </header>
    <section class="main">
        <input class="toggle-all" type ="checkbox">
        <label for="toggle-all">Mark all as complete</label>
        <ul class="item-list">
            <% @lists.each do |display| %>
            <li>
                <div class="view">
                    <label><%= link_to display.name, list_path(display) %></label>
                </div>
            </li>
            <% end %>
        </ul>
    </section>
         <footer class="footer">
         </footer>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroceryLister</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/Findex.html.1.erb
<section class="grocerylisterapp">
    <header class="header">
        <h1>Your Lists</h1>
      <%= form_for(@list) do |f| %>
 
      <%= f.text_field :name, :class => "new-item" %>
 
      <%= f.submit :style => "display: none" %>
      
      <div id="error_explanation">
          <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>
          <ul>
              <% @list.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
        
        <%  end %>
</form>
    </header>
    <section class="main">
        <input class="toggle-all" type ="checkbox">
        <label for="toggle-all">Mark all as complete</label>
        <ul class="item-list">
            <% @lists.each do |display| %>
            <li>
                <div class="view">
                    <label><%= link_to display.name, list_path(display) %></label>
                </div>
            </li>
            <% end %>
        </ul>
    </section>
         <footer class="footer">
         </footer>
</section>

app/views/lists/index.html.erb
<section class="grocerylisterapp">
    <header class="header">
        <h1>Your Lists</h1>
      <%= form_for(@list) do |f| %>
    <% @list.errors[:name].any? %>
      <%= f.text_field :name, :class => "new-list", :placeholder => "create new list..." %>
      <%= f.submit :style => "display: none" %>
<div>
    <ul style="list-style: none;">
        <% @list.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
                 <% end %>
    </ul>
</div>
         <%  end %>
</form>
    </header>
    <section class="main">
        <input class="toggle-all" type ="checkbox">
        <label for="toggle-all">Mark all as complete</label>
        <ul class="item-list" style="list-style: none;">
            <% @lists.each do |display| %>
            <li>
                <div class="view">
                    <label><%= link_to display.name, list_path(display) %></label>
                </div>
            </li>
            <% end %>
        </ul>
    </section>
         <footer class="footer">
         </footer>
</section>

app/views/lists/show.html.erb
<section class="grocerylisterapp">
    <header class="header">
        <h1><%= @list.name%></h1>
        <%= form_for([@list, @item]) do |f| %>
        <%= f.text_field :description, :class => "new-item", :placeholder => (@item.errors.full_messages_for(:description).first || "add item...") %>
                <%= f.submit :style => "display: none" %>
                    <% end %>

        <input class="toggle-all" type="checkbox">
        <%if @item.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@item.errors.count, "error") %>
                prohibited this item from being saved:
                <% @item.errors.full_messages.each do |msg| %>
            </h2>
            <ul style="list-style: none;">
                <li><%= msg %></li>
                     <% end %>
            </ul>
                    <%  end %>
    </header>
    <section class="grocerylisterapp">
        <label for="toggle-all">Mark all as complete</label>
        <ul class="item-list" style="list-style: none;">
            <%= render :collection =>  @list.items, :partial => "items/item_li", :as => :item %>
        </ul>
    </section>
    <footer class="footer">
    </footer>
    </section>

app/views/site/index.html.erb
<body class="learn-bar">
    <header class="header">
        <h1>Your Lists</h1>
        <input class="new-item" placeholder="make a new list?" autofocus="">
    </header>
    
    
    
    <section class="grocerylisterapp">
            <ul class="item-list">
                <li>
                    <div class="view">
                        <label><a href="#">Grocery Store List</a></label>
                     </div>
                </li>
                <li>
                    <div class="view">
                        <label><a href=""#>Farmer's Market List</a></label>
                    </div>
                </li>

                <li>
                    <div class="view">
                        <label> <a href="">Wholesale Store List</a></label>
                    </div>
                </li>

                <li>
                    <div class="view">
                        <label> <a href="">Pharmacy List</a></label>
                    </div>
                </li>

            </ul>
    </section>

app/views/site/this_used_to_be_index.html.erb
<body class="learn-bar">
    <header class="header">
        <h1>WRONG PAGE IS BEING RENDERED - Your Lists</h1>
        <input class="new-item" placeholder="make a new list?" autofocus="">
    </header>
    
    
    
    <section class="grocerylisterapp">
            <ul class="item-list">
                <li>
                    <div class="view">
                        <label><a href="#">Grocery Store List</a></label>
                     </div>
                </li>
                <li>
                    <div class="view">
                        <label><a href=""#>Farmer's Market List</a></label>
                    </div>
                </li>

                <li>
                    <div class="view">
                        <label> <a href="">Wholesale Store List</a></label>
                    </div>
                </li>

                <li>
                    <div class="view">
                        <label> <a href="">Pharmacy List</a></label>
                    </div>
                </li>

            </ul>
    </section>